# Generated by Django 3.2.3 on 2021-10-19 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_items_initialbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='initialBid',
        ),
    ]
