# Generated by Django 3.2.3 on 2021-10-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_items_initialbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='initialBid',
            field=models.CharField(default='something', max_length=4),
        ),
    ]
