# Generated by Django 3.2.3 on 2021-10-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_items_initialbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='initialBid',
            field=models.FloatField(default=0.0),
        ),
    ]
